apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: all-apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/Yoann-Merle/test-argo-cd.git
      revision: HEAD
      directories:
      - path: apps/*
  template:
    metadata:
      name: '{{.path.basenameNormalized}}'
      namespace: argocd
    spec:
      project: default

      source:
        repoURL: https://github.com/Yoann-Merle/test-argo-cd.git
        targetRevision: HEAD
        path: '{{.path.path}}'
        directory:
          recurse: true
      destination:
        server: https://kubernetes.default.svc

      syncPolicy:
        automated:
          selfHeal: true
          prune: true
