apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: all-applications
  namespace: argocd

spec:
  generators:
  - list:
      elements:
      - name: dev
      - name: dev2
      - name: dev3
  template:
    metadata:
      name: '{{name}}'
      namespace: argocd
    spec:
      project: default

      source:
        repoURL: https://github.com/Yoann-Merle/test-argo-cd.git
        targetRevision: HEAD
        path: 'apps/{{name}}'
      destination:
        server: https://kubernetes.default.svc

      syncPolicy:

        automated:
          selfHeal: true
          prune: true
