apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application-2
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Yoann-Merle/test-argo-cd.git
    targetRevision: HEAD
    path: dev2
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp2

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
