apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-argo-apps
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Yoann-Merle/test-argo-cd.git
    targetRevision: HEAD
    path: argo-apps
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
